topoguide/itineraires/urls.py
from django.urls import path
from . import views

app_name = 'itineraires'
urlpatterns = [
    path('', views.listeItineraires, name='listeItineraires'),
    path('<int:itineraire_id>/', views.listeSorties, name='listeSorties'),
    path('sortieDetails/<int:sortie_id>', views.sortieDetails, name='sortieDetails'),
    path('ajouterModifSortie/<int:sortie_id>/', views.ajouterModifSortie, name='ajouterModifSortie'),
]

topoguide/topoguide/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('itineraires/', include('itineraires.urls')),
]   

topoguide/itineraires/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core import validators


class Itineraire(models.Model):
    """
    Un itinéraire auquel est attaché 0, 1 ou plusieurs sorties
    """
    titre = models.CharField(max_length=200)
    point_de_depart = models.CharField(max_length=200)
    description = models.TextField()
    altitude_de_depart = models.FloatField(validators=[validators.MinValueValidator(0)])
    altitude_min = models.FloatField(validators=[validators.MinValueValidator(0)])
    altitude_max = models.FloatField(validators=[validators.MinValueValidator(0)])
    denivele_positif_cumule = models.FloatField(validators=[validators.MinValueValidator(0)])
    denivele_negatif_cumule = models.FloatField(validators=[validators.MinValueValidator(0)])
    duree_estime = models.FloatField(validators=[validators.MinValueValidator(0)])
    CHOIX_DIFFICULTEE = ((1,"Très facile"), (2, "Facile"), (3, "Moyenne"), (4, "Difficile"), (5, "Très difficile"))
    difficulte_estimee = models.IntegerField(default=3, choices=CHOIX_DIFFICULTEE)

    def __str__(self):
        return self.titre

class Sortie(models.Model):
    """
    Une sortie qui correspond à un utilisateur et une sortie
    """
    utilisateur = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    itineraire = models.ForeignKey("Itineraire", on_delete=models.CASCADE)
    date_sortie = models.DateField()
    duree_reelle = models.FloatField(validators=[validators.MinValueValidator(0)])
    nombre_participant = models.IntegerField(default=1, validators=[validators.MinValueValidator(1)])
    CHOIX_EXPERIENCE = (("debutants", "debutants"), ("tous expérimentés", "tous expérimentés"), ("mixte","mixte"))
    experience_groupe = models.CharField(default="mixte", choices=CHOIX_EXPERIENCE, max_length=200)
    CHOIX_METEO = (("bonne","bonne"), ("moyenne","moyenne"), ("mauvaise", "mauvaise"))
    meteo = models.CharField(default="bonne", choices=CHOIX_METEO, max_length=200)
    CHOIX_DIFFICULTEE = ((1,"Très facile"), (2, "Facile"), (3, "Moyenne"), (4, "Difficile"), (5, "Très difficile"))
    difficulte_estimee = models.IntegerField(default=3, choices=CHOIX_DIFFICULTEE)

    def __str__(self):
        return f"{self.itineraire} : {self.utilisateur}"

topoguide/itineraires/forms.py
from django import forms

from .models import Sortie

class SortieForm(forms.ModelForm):
    """
    Formulaire pour la saisie d'une sortie par un utilsateur connecté
    """
    class Meta:
        model = Sortie
        fields = ['itineraire', 'date_sortie', 'duree_reelle', 'difficulte_estimee', 'nombre_participant', 'experience_groupe', 'meteo' ]

topoguide/itineraires/views.py
from distutils.log import Log
from django.shortcuts import get_object_or_404, redirect, render

from .models import Itineraire, Sortie
from .forms import SortieForm
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required


def listeItineraires(request):
    """
    Renvoie la liste de tous les itinéraires disponibles (rentrés un admin)
    Possibilité :
    -d'acceder aux sorties correspondant à l'itinéraire en cliquant sur l'itinéraire voulu
    -de se connecter/déconnecter
    Si l'utilisateur est connecté ajouter des sorties
    """
    ListeItineraires = Itineraire.objects.all()
    context = {"ListeItineraires" : ListeItineraires, 'utilisateur':request.user}
    return render(request, "itineraires/listeItineraires.html", context)


def listeSorties(request, itineraire_id):
    """
    Renvoie la liste des sorties correspondant à un itinéraire
    Possibilité :
    -de consulter de le détail d'une sortie
    -de modifier une de ses sorties
    -de se connecter/déconnecter
    -de revenir à la liste des itinéraires (menu pricipal)
    Si l'utilisateur est connecté, il peut modifier ses sorties et ajouter des sorties
    """
    itineraireSortie = get_object_or_404(Itineraire, pk = itineraire_id)
    ListeSorties = Sortie.objects.filter(itineraire = itineraireSortie)
    context = {"itineraire":itineraireSortie, "ListeSorties":ListeSorties}
    return render(request, "itineraires/listeSorties.html", context)


def sortieDetails(request, sortie_id):
    """
    Détail d'une sortie
    Possibilité :
    -de se connecter/déconnecter
    -de revenir à la liste des itinéraires (menu pricipal)
    """
    sortie = get_object_or_404(Sortie, pk=sortie_id)
    context = {"sortie":sortie}
    return render(request, "itineraires/sortieDetails.html", context)


def ajouterSortie(request):
    """
    Formulaire pour ajouter une sortie
    Possibilité :
    -d'enregistrer sa sortie avec les informations saisies
    -de se connecter/déconnecter
    -de revenir à la liste des itinéraires (menu pricipal)
    """
    if request.method == 'POST':
        form = SortieForm(request.POST)
        if form.is_valid():
            sortie = form.save(commit=False)
            sortie.utilisateur = request.user
            sortie.save()
            context = {'sortie':sortie}
            return render(request, 'itineraires/sortieDetails.html', context)

    else:
        
        form = SortieForm()
    context = {'form':form, 'sortie_id':0}
    return render(request, 'itineraires/ajouterModifSortie.html', context)
    
    
@login_required(redirect_field_name='login')
def ajouterModifSortie(request,sortie_id):
    """
    Formulaire pour modifier une sortie
    Possibilité :
    -d'enregistrer sa sortie modifiée avec les informations saisies
    -de se connecter/déconnecter
    -de revenir à la liste des itinéraires (menu pricipal)
    """
    if sortie_id == 0:
        return ajouterSortie(request)
    sortie = get_object_or_404(Sortie, pk=sortie_id)
    if sortie.utilisateur != request.user:
        return redirect("login")
    if request.method == 'POST':
        form = SortieForm(request.POST, instance=sortie)
        if form.is_valid():
            sortie = form.save(commit=False)
            sortie.utilisateur = request.user
            sortie.save()
            context = {'sortie':sortie}
            return render(request, 'itineraires/sortieDetails.html', context)

    else:
        form = SortieForm(instance=sortie)
    context = {'form':form, 'sortie_id':sortie_id, 'sortie':sortie}
    return render(request, 'itineraires/ajouterModifSortie.html', context)

topoguide/itineraires/templates/itineraires/ajouterModifSortie.html
{% extends 'base.html' %}
{% load bootstrap5 %}



{% block content %}



<div class="container p-5 my-5 border">
    <h1>Saisissez votre sortie:</h1>

    <!--Formulaire pour saisir ou modifier une sortie-->
    <div class="clearfix">
        <div class="float-right pb-3">
            <form action="{% url 'itineraires:ajouterModifSortie' sortie_id %}" method="post" class="form">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>

    <!--Bouton pour revenir en arrière (ne fonctionne que pour la modification de sortie)-->
    {% if sortie.itineraire.id %}
        <a href={% url 'itineraires:listeSorties' sortie.itineraire.id %} class="btn btn-warning">Retour</a>
    {% endif %}

</div>


{%endblock content%}

topoguide/itineraires/templates/itineraires/listeItineraires.html
{% extends 'base.html' %}
{% load static %}

<!--importation d'un fichier de style pour modifier l'apparence des liens cliquables-->
{% block staticFiles %}
    <link rel="stylesheet" type="text/css" href={% static "itineraires/listeItineraires.css" %}>
{% endblock staticFiles %}

{% block content %}
    
<div class="container mt-3">
    <h1>Liste des itinéraires:</h1>
    
    <!--Tableau représentant la liste des itinéraires disponnibles-->
    <div class="table-responsive">
        <table class="table table-striped">
            <tr>
                <th>Itinéraire</th>
                <th>Durée estimée</th>
                <th>Difficultée estimée</th>
            {% for itineraire in ListeItineraires %}
                <!--Chaque case de l'itinéraire est "cliquable" et renvoie vers la sortie correspondante-->
                <tr class="tr-bkg">
                    <td><a href={% url "itineraires:listeSorties" itineraire.id %}>{{ itineraire.titre }} </a></td>
                    <td><a href={% url "itineraires:listeSorties" itineraire.id %}>{{ itineraire.difficulte_estimee}} h </a></td>
                    <td><a href={% url "itineraires:listeSorties" itineraire.id %}>{{ itineraire.difficulte_estimee}}/5 </a></td>
                </tr>
            {% endfor %}
            </table>
    </div>

{% endblock content %}

topoguide/itineraires/templates/itineraires/listeSorties.html
{% extends 'base.html' %}

{% block content %}


<!--Tableau représentant les détails de l'itinéraire pour lequel les sorties sont associées-->
<div class="container mt-3">
    <h1>{{ itineraire }}</h1>
    <table class="table table-striped">
        <tr>
            <th>description:</th>
            <td>{{ itineraire.description }}</td>
        </tr>
        <tr>
            <th>altitude de depart:</th>
            <td>{{ itineraire.altitude_de_depart }} m</td>
        </tr>
        <tr>
            <th>altitude min:</th>
            <td>{{ itineraire.altitude_min }} m</td>
        </tr>
        <tr>
            <th>altitude max:</th>
            <td>{{ itineraire.altitude_max }} m</td>
        </tr>
        <tr>
            <th>denivele positif cumule:</th>
            <td>{{ itineraire.denivele_positif_cumule }} m</td>
        </tr>
        <tr>
            <th>denivele negatif cumule:</th>
            <td>-{{ itineraire.denivele_negatif_cumule }} m</td>
        </tr>
        <tr>
            <th>duree estime:</th>
            <td>{{ itineraire.duree_estime }} h</td>
        </tr>
        <tr>
            <th>difficulte estimee:</th>
            <td>{{ itineraire.difficulte_estimee }}/5</td>
        </tr>
    </table>
</div>


<!--Liste des sorties associées à l'itinéraire-->
<div class="container mt-3">
    <h2>Liste des sorties:</h2>

    <div class="table-responsive">
        <table class="table table-striped">
            <tr>
                <th>Utilisateur</th><th>Date de la sortie</th><th>Durée réelle</th><th>Difficultée estimée</th><th></th><th></th>
            </tr>
            {% for sortie in ListeSorties %}
            <tr>
                <td>{{ sortie.utilisateur }}</td>
                <td>{{ sortie.date_sortie }}</td>
                <td>{{ sortie.duree_reelle }} h</td>
                <td>{{ sortie.difficulte_estimee }}/5</td>
                <!--Bouton consulter qui renvois vers la page de détails de la sortie-->
                <td><a href={% url 'itineraires:sortieDetails' sortie.id %} class="btn btn-primary">Consulter</a>
                <!--Bouton modifier qui renvois vers la page de modification de la sortie. 
                    Ne s'affiche que si la sortie a été saisie par l'utilisateur présentement connecté-->
                {% if request.user == sortie.utilisateur %}
                <a href={% url 'itineraires:ajouterModifSortie' sortie.id %} class="btn btn-success">Modifier</a>
                {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>

{% endblock content %}

topoguide/itineraires/templates/itineraires/sortieDetails.html
{% extends 'base.html' %}


{% block content %}

<!--Tableau contenant les détails d'une sortie-->
<div class="container mt-3">
    <h1>{{ sortie }}</h1>
    <table class="table">
        <tr>
            <th>utilisateur :</th><td>{{sortie.utilisateur}}</td>
        </tr>
        <tr>
            <th>itineraire :</th><td>{{sortie.itineraire}}</td>
        </tr>    
        <tr>
            <th>date de la sortie :</th><td>{{sortie.date_sortie}}</td>
        </tr>
        <tr>
            <th>duree réelle :</th><td>{{sortie.duree_reelle}} h</td>
        </tr>
        <tr>
            <th>nombre de participant(s) :</th><td>{{sortie.nombre_participant}}</td>
        </tr>
        <tr>
            <th>experience du groupe :</th><td>{{sortie.experience_groupe}}</td>
        </tr>
        <tr>
            <th>météo :</th><td>{{sortie.meteo}}</td>
        </tr>
        <tr>
            <th>difficulté estimée :</th><td>{{sortie.difficulte_estimee}}/5</td>
        </tr>
    
    </table>

    <!--Bouton de retour en arrière (pour revenir à la page de listing des sorties associée 
        à l'itinéraire de la sortie que l'utilsateur consulte actuellement)-->
    <a href={% url 'itineraires:listeSorties' sortie.itineraire.id %} class="btn btn-warning">Retour</a>

    <!--Bouton qui renvoie vers la page de modification d'une sortie.
        N'est visible que si l'utilsateur est connecté et qu'il a saisie la présente sortie-->
    {% if request.user == sortie.utilisateur %}
        <a href={% url 'itineraires:ajouterModifSortie' sortie.id %} class="btn btn-success">Modifier</a>
    {% endif %}
    
</div>


    

{% endblock content %}

topoguide/templates/base.html
{% load bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="fr">
    <head>
        <!--En-tête que dont héritera tous les fichiers html
            -Ajout d'un titre à la page
            -Icone de randonneur
            -Définition des méta-données
            -Ajout de bootstrap5
            -Block permetant d'ajouter des fichiers statiques-->
        <meta charset="utf-8">
        <title>{% block title %}Topoguide{% endblock title%}</title>
        <link rel="icon" type="image/x-icon" href={% static 'icone-randonneur.png' %}>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        {% block staticFiles %}
        {% endblock staticFiles %}
        
    </head>

    <style>
        /*Affichage d'une image de fond*/
        body {
          background-image: url({% static 'hiking-wallpapers.jpg' %});
          background-repeat: no-repeat;
          background-attachment: fixed;
          background-size: cover;
        }
    </style>

    <body>
        <!--Barre de navigation-->
            {% block menu%}
            <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
                <table>
                    <!--Affichage du nom de l'utilisateur si il est connecté ou de login sinon. 
                        Les deux textes renvois vers la page de login-->
                    <td>
                        {% if request.user.is_active %}
                            <a class="nav-link active text-light" href={% url "login" %}>Bienvenue {{ request.user }}</a>
                        {% else %}
                            <a class="nav-link active text-light" href={% url "login" %}>Connexion</a>
                        {% endif %}
                    </td>
                    
                    <!--Lien pour ajouter une sortie.
                        Renvois vers la page de login si l'utilisateur n'est pas connecté-->
                    <td>       
                        <a class="nav-link active text-light" href={% url "itineraires:ajouterModifSortie" 0 %}>Ajouter une sortie</a>
                    </td>

                    <!--Lien qui renvoie vers la liste des itinéraires-->
                    <td>
                        <a class="nav-link active text-light" href={% url "itineraires:listeItineraires" %}>Menu principal</a>
                    </td>
                    <!--Bouton de déconnexion (seulement si l'utilisateur est connecté)-->

                    <td>
                        {% if request.user.is_active %}
                            <a class="nav-link active text-light item-right" href={% url "logout" %} >Déconnexion</a>
                        {% endif %}
                    </td>
                </tr>
                </table>
            </nav>
            {% endblock menu %}

            <!--Block pour acceuillir le code propre à chaque page html-->
            <div class="container-fluid" style="margin-top:80px">
                {% block content %}{% endblock %}
            </div>
    </body>
    
</html>